// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elsilxqruurrbdebxndx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsc2lseHFydXVycmJkZWJ4bmR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDc2ODIsImV4cCI6MjA2NTUyMzY4Mn0.iDGYrWgxQNrb38k_Obkz3Ipuuo_6uDXfHGUrYVwtZ5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);